include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**.g.dart"
    - "**.freezed.dart"
    - lib/src/presentation/l10n/app_localizations**

linter:
  rules:
    public_member_api_docs: false
    one_member_abstracts: false
